[tool.poetry]
name = "ragger"
description = "A repository for general-purpose RAG applications."
version = "1.0.0"
authors = [
    "Dan Saattrup Nielsen <dan.nielsen@alexandra.dk>",
    "Anders Jess Pedersen <anders.j.pedersen@alexandra.dk>",
]
readme = "README.md"
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = "^1.26.4"
python-dotenv = "^1.0.1"
pydantic = "^2.8.2"
httpx = ">=0.27.0,<1.0.0"
sentence-transformers = "^2.7.0"
gradio = { version = "^4.27.0", optional = true }
tiktoken = { version = ">=0.7.0,<1.0.0", optional = true }
openai = { version = "^1.23.2", optional = true }
vllm = { markers = "sys_platform != 'darwin'", version = "^0.4.0", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = ">=8.1.1"
pytest-cov = ">=4.1.0"
pre-commit = ">=3.6.2"
readme-coverage-badger = ">=0.1.2"
click = ">=8.1.7"
ruff = ">=0.3.2"
mypy = ">=1.9.0"
nbstripout = ">=0.7.1"

[tool.poetry.extras]
vllm = [
    "vllm",
]
openai = [
    "openai",
    "tiktoken",
]
demo = [
    "gradio"
]
all = [
    "vllm",
    "openai",
    "tiktoken",
    "gradio",
]


[[tool.poetry.source]]
name = "pypi"

[tool.ruff]
target-version = "py311"
line-length = 88
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
extend-select = [
    "I",
    "D",
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = [
    "F401",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    '--durations=10',
    '--color=yes',
    '--doctest-modules',
    '--cov=src/ragger',
]
xfail_strict = true
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ImportWarning",
    "ignore::ResourceWarning",
    "ignore::FutureWarning",
]
log_cli_level = "info"
testpaths = [
    "tests",
    "src/ragger",
]

[build-system]
requires = [
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"
