[tool.poetry]
name = "ragger"
description = "A package used to for RAG applications."
version = "0.0.0"
authors = [
    "Dan Saattrup Nielsen <dan.nielsen@alexandra.dk>",
]
readme = "README.md"
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
hydra-core = "^1.3.2"

[build-system]
requires = [
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.1.1"
pytest-cov = ">=4.1.0"
pre-commit = ">=3.6.2"
pdoc = ">=14.1.0"
readme-coverage-badger = ">=0.1.2"
click = ">=8.1.7"
ruff = ">=0.3.2"
mypy = ">=1.9.0"
nbstripout = ">=0.7.1"

[[tool.poetry.source]]
name = "pypi"


[tool.ruff]
target-version = "py311"
line-length = 88
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
extend-select = [
    "I",
    "D",
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = [
    "F401",
]
"src/scripts/your_script.py" = [
    "I",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    '--verbose',
    '--durations=10',
    '--color=yes',
    '-s',
    '-vv',
    '--doctest-modules',
    '--cov=src/ragger',
]
xfail_strict = true
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ImportWarning",
]
log_cli_level = "info"
testpaths = [
    "tests",
    "src/ragger",
]
[tool.pylic]
safe_licenses = [
    "1-clause BSD License",
    "Academic Free License v. 3.0",
    "Adaptive Public License 1.0",
    "Apache License, Version 2.0",
    "Apache Software License",
    "Apache Software License, version 1.1",
    "Apple Public Source License 2.0",
    "Artistic License (Perl) 1.0",
    "Artistic License 1.0",
    "Artistic License 2.0",
    "Attribution Assurance License",
    "Boost Software License 1.0",
    "BSD+Patent",
    "Cea Cnrs Inria Logiciel Libre License, version 2.1",
    "CERN Open Hardware Licence Version 2 - Permissive",
    "CERN Open Hardware Licence Version 2 - Strongly Reciprocal",
    "CERN Open Hardware Licence Version 2 - Weakly Reciprocal",
    "Common Development and Distribution License 1.0",
    "Common Public Attribution License Version 1.0",
    "Common Public License Version 1.0",
    "Computer Associates Trusted Open Source License 1.1",
    "Cryptographic Autonomy License",
    "CUA Office Public License",
    "Eclipse Public License -v 1.0",
    "Eclipse Public License version 2.0",
    "eCos License version 2.0",
    "Educational Community License, Version 1.0",
    "Educational Community License, Version 2.0",
    "Eiffel Forum License, version 1",
    "Eiffel Forum License, Version 2",
    "Entessa Public License Version. 1.0",
    "EU DataGrid Software License",
    "European Union Public License, version 1.2",
    "Fair License",
    "Frameworx License 1.0",
    "GNU Affero General Public License version 3",
    "GNU General Public License version 2",
    "GNU General Public License version 3",
    "GNU General Public License, version 1",
    "GNU Lesser General Public License version 2.1",
    "GNU Lesser General Public License version 3",
    "GNU LGPL",
    "GNU Library General Public License version 2",
    "Historical Permission Notice and Disclaimer",
    "IBM Public License Version 1.0",
    "ICU License",
    "Intel Open Source License",
    "IPA Font License",
    "ISC License",
    "Jabber Open Source License",
    "JAM License",
    "LaTeX Project Public License, Version 1.3c",
    "Lawrence Berkeley National Labs BSD Variant License",
    "Licence Libre du Québec - Permissive version 1.1",
    "Licence Libre du Québec - Réciprocité forte version 1.1",
    "Licence Libre du Québec - Réciprocité version 1.1",
    "Lucent Public License Version 1.02",
    "Lucent Public License, Plan 9, version 1.0",
    "Microsoft Public License",
    "Microsoft Reciprocal License",
    "MirOS License",
    "MIT No Attribution License",
    "MITRE Collaborative Virtual Workspace License",
    "Motosoto Open Source License",
    "Mozilla Public License 1.1",
    "Mozilla Public License 2.0",
    "Mozilla Public License, version 1.0",
    "Mulan Permissive Software License v2",
    "Multics License",
    "NASA Open Source Agreement v1.3",
    "NAUMEN Public License",
    "Nokia Open Source License Version 1.0a",
    "Non-Profit Open Software License version 3.0",
    "NTP License",
    "Open Group Test Suite License",
    "Open Logistics Foundation License v1.3",
    "Open Software License 2.1",
    "Open Software License, version 1.0",
    "OpenLDAP Public License Version 2.8",
    "OSET Public License version 2.1",
    "PHP License 3.0",
    "PHP License 3.01",
    "Python License, Version 2",
    "RealNetworks Public Source License Version 1.0",
    "Reciprocal Public License 1.5",
    "Reciprocal Public License, version 1.1",
    "SIL OPEN FONT LICENSE",
    "Simple Public License",
    "Sun Industry Standards Source License",
    "Sun Public License, Version 1.0",
    "The 2-Clause BSD License",
    "The 3-Clause BSD License",
    "The CNRI portion of the multi-part Python License",
    "The European Union Public License, version 1.1",
    "The MIT License",
    "MIT License",
    "The Nethack General Public License",
    "The OCLC Research Public License 2.0 License",
    "The Open Software License 3.0",
    "The PostgreSQL Licence",
    "The Q Public License Version",
    "The Ricoh Source Code Public License",
    "The Sleepycat License",
    "The Sybase Open Source Licence",
    "The Universal Permissive License Version 1.0",
    "The University of Illinois/NCSA Open Source License",
    "The Unlicense",
    "The Vovida Software License v. 1.0",
    "The W3C® SOFTWARE NOTICE AND LICENSE",
    "The wxWindows Library Licence",
    "The X.Net, Inc. License",
    "The zlib/libpng License",
    "UNICODE LICENSE V3",
    "Unicode, Inc. License Agreement - Data Files and Software",
    "Upstream Compatibility License v1.0",
    "Zero-Clause BSD",
    "Zope Public License 2.0",
    "Zope Public License 2.1",
]
unsafe_packages = [
    "unlicensedPackage",
]
