name: openai
api_key_variable_name: OPENAI_API_KEY
model: gpt-4-turbo-2024-04-09
temperature: 0.0
max_tokens: 256
stream: true
timeout: 60
system_prompt: ${..language.system_prompt}
prompt: ${..language.prompt}
