name: openai
api_key_variable_name: OPENAI_API_KEY
model: gpt-4-turbo-2024-04-09
temperature: 0.0
max_input_tokens: 130_000
max_output_tokens: 256
stream: true
timeout: 60
max_retries: 3
system_prompt: ${..language.system_prompt}
prompt: ${..language.prompt}
