name: vllm
model: ThatsGroes/munin-SkoleGPTOpenOrca-7b-16bit
temperature: 0.0
max_tokens: 256
stream: true
timeout: 60
system_prompt: ${..language.system_prompt}
prompt: ${..language.prompt}
max_model_len: 10_000
gpu_memory_utilization: 0.95
server: null
