name: danish

# Demo parameters
title: >
  RAG Bot
feedback_instruction: >
  Benyt 游녨/游녩 til at indikere om svaret er godt eller d친rligt!
thank_you_feedback: >
  Tak for dit svar! Skriv dit sp칮rgsm친l nedenfor og tryk p친 'Indsend'.
input_box_placeholder: >
  Skriv dit sp칮rgsm친l her
submit_button_value: >
  Indsend
no_documents_reply: >
  Jeg er desv칝rre ikke i stand til at svare p친 dit sp칮rgsm친l ud fra den viden, som
  jeg har til r친dighed. Beklager!
description: |
  En robot, der kan svare p친 alle dine sp칮rgsm친l!

  Skriv dit sp칮rgsm친l i tekstboksen og tryk p친 'Indsend' eller Enter knappen.

# Generator parameters
system_prompt: |
    Du er en seniorkonsulent, som har til opgave at finde svar p친 sp칮rgsm친l ud fra en
    r칝kke dokumenter.

    Dit svar er i JSON-format, med keys "sources" og "answer" i din JSON dictionary.
    Her er "sources" en liste af ID'er p친 de kildedokumenter, som du skal bruge for at
    kunne besvare sp칮rgsm친let, og "answer" dit svar ud fra disse kildedokumenter. Hvis
    du ikke angiver nogen kildedokumenter i "sources", s친 indikerer du, at sp칮rgsm친let
    ikke kan besvares ud fra kildedokumenterne, og i s친 fald s칝tter du "answer" til en
    tom streng.

    Du svarer altid p친 dansk.
prompt: |
    Her er en r칝kke dokumenter, som du skal basere din besvarelse p친.

    <documents>
    {documents}
    </documents>

    Ud fra disse dokumenter, hvad er svaret p친 f칮lgende sp칮rgsm친l?

    <question>
    {query}
    </question>

    Husk dine instrukser.

    <answer>
