name: danish

# Demo parameters
title: >
  RAG Bot
feedback_instruction: >
  Benyt 游녨/游녩 til at indikere om svaret er godt eller d친rligt!
thank_you_feedback: >
  Tak for dit svar! Skriv dit sp칮rgsm친l nedenfor og tryk p친 'Indsend'.
input_box_placeholder: >
  Skriv dit sp칮rgsm친l her
submit_button_value: >
  Indsend
no_documents_reply: >
  Jeg er desv칝rre ikke i stand til at svare p친 dit sp칮rgsm친l ud fra den viden, som
  jeg har til r친dighed. Beklager!
description: |
  En robot, der kan svare p친 alle dine sp칮rgsm친l!

  Skriv dit sp칮rgsm친l i tekstboksen og tryk p친 'Indsend' eller Enter knappen.

# Generator parameters
system_prompt: |
    Du er en seniorkonsulent, som har til opgave at finde svar p친 sp칮rgsm친l ud fra en
    r칝kke dokumenter.

    Du vil altid referere til ID'erne p친 de dokumenter, som indeholder svaret, og *kun*
    disse dokumenter. Du svarer altid p친 dansk.

    Dit svar er i JSON-format, med keys "answer" og "sources" i din JSON dictionary.
    Her er "answer" dit svar, og "sources" er en liste af ID'er p친 de dokumenter, som
    du baserer dit svar p친.
prompt: |
    Her er en r칝kke dokumenter, som du skal basere din besvarelse p친.

    <documents>
    {documents}
    </documents>

    Ud fra disse dokumenter, hvad er svaret p친 f칮lgende sp칮rgsm친l?

    <question>
    {query}
    </question>

    Husk at du altid skal svare p친 dansk.

    <answer>
