name: Build

on:
  release:
    types: ["published"]

jobs:
  build-wheels:
    strategy:
        matrix:
            os: ["ubuntu-latest", "macos-latest", "windows-latest"]
            python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        run: uv build --wheel .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
