name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - staging

jobs:
  code-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  pytest:
    if: github.event.pull_request.draft == false
    strategy:
        matrix:
            os: [self-hosted-ubuntu-latest]
            python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Log disk space
        run: df -h

      - name: Setup PostgreSQL server
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-common
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt-get install -y postgresql-16 postgresql-16-pgvector
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

      - name: Install Poetry
        run: pipx install poetry==1.8.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --extras all --extras cpu

      - name: Fix PyTorch bug
        run: poetry add torch==2.0.0

      - name: Test with pytest
        run: poetry run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
